# Generated by Django 4.2 on 2026-05-14 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('funcionando', 'Funcionando'), ('problema', 'Com Problema')], default='funcionando', max_length=20)),
                ('posicao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ultima_previsao_tempo', models.FloatField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
